version: '3.9'
services:
    email:
        image: 'maildev/maildev'
        ports:
            - '8082:1080'

    db:
        image: 'postgres:14.5-alpine'
        environment:
            POSTGRES_DB: cookery2
            POSTGRES_USER: cookery2
            POSTGRES_PASSWORD: cookery2123
        ports:
            - '5432:5432'
        volumes:
            - postgre_cookery_2_data:/var/lib/postgresql/data

    pgadmin:
        image: 'dpage/pgadmin4'
        environment:
            PGADMIN_DEFAULT_EMAIL: user@domain.com
            PGADMIN_DEFAULT_PASSWORD: cookery2123
            PGADMIN_CONFIG_SERVER_MODE: 'False'
            MASTER_PASSWORD_REQUIRED: 'False'
        ports:
            - '8083:80'
        volumes:
            - ../servers.json:/pgadmin4/servers.json
            - pgadmin_cookery_2_data:/var/lib/pgadmin
        depends_on:
            - db

    backend:
        image: 'my-cookery-book-2-backend:latest'
        restart: always
        ports:
            - '8080:8080'
        environment:
            PORT: 8080
            BASE_PATH: '/api'
            DATABASE_PASSWORD: 'cookery2123'
            DATABASE_USER: 'cookery2'
            DATABASE: 'cookery2'
            DATABASE_HOST: 'db'
            DATABASE_PORT: 5432
            DATABASE_LOGGING: 'true'
            TOKEN_SIGN_KEY: 'somesecrettoken'
            TOKEN_VALIDITY: '60m'
            REFRESH_TOKEN_VALIDITY: '30d'
        depends_on:
            - db
            - email
volumes:
    postgre_cookery_2_data:
    pgadmin_cookery_2_data:
