version: '3.9'
services:
    email:
        image: 'maildev/maildev'
        ports:
            - '8082:1080'

    db:
        image: 'postgres:14.5-alpine'
        environment:
            POSTGRES_DB: cookery2
            POSTGRES_USER: cookery2
            POSTGRES_PASSWORD: cookery2123
        volumes:
            - postgre_cookery_2_data:/var/lib/postgresql/data

    pgadmin:
        image: 'dpage/pgadmin4'
        environment:
            PGADMIN_DEFAULT_EMAIL: user@domain.com
            PGADMIN_DEFAULT_PASSWORD: cookery2123
            PGADMIN_CONFIG_SERVER_MODE: 'False'
            MASTER_PASSWORD_REQUIRED: 'False'
        ports:
            - '8083:80'
        volumes:
            - ./servers.json:/pgadmin4/servers.json
            - pgadmin_cookery_2_data:/var/lib/pgadmin
        depends_on:
            - db

    backend:
        image: 'my-cookery-book-2-backend:latest'
        restart: always
        environment:
            PORT: 8080
            BASE_PATH: '/api'
            DATABASE_PASSWORD: 'cookery2123'
            DATABASE_USER: 'cookery2'
            DATABASE: 'cookery2'
            DATABASE_HOST: 'db'
            DATABASE_PORT: 5432
            DATABASE_LOGGING: 'true'
            TOKEN_SIGN_KEY: 'somesecrettoken'
            TOKEN_VALIDITY: '1h'
            REFRESH_TOKEN_VALIDITY: '10d'
        depends_on:
            - db
            - email
        labels:
            - traefik.enable=true
            - traefik.http.routers.cookery-api.rule=PathPrefix(`/api`)
            - traefik.http.routers.cookery-api.entrypoints=web
            - traefik.http.services.cookery-api.loadbalancer.server.port=8080

    frontend:
        image: 'my-cookery-book-2-frontend:latest'
        restart: always
        environment:
            NGINX_PORT: 80
            BASE_API_URL: '/api'
        depends_on:
            - backend
        labels:
            - traefik.enable=true
            - traefik.http.routers.cookery-frontend.rule=PathPrefix(`/`)
            - traefik.http.routers.cookery-frontend.entrypoints=web
            - traefik.http.services.cookery-frontend.loadbalancer.server.port=80

    traefik:
        image: traefik:v2.8.4
        command:
            - "--api.insecure=true"
            - "--providers.docker=true"
            - "--providers.docker.exposedbydefault=false"
            - "--entrypoints.web.address=:80"
            - "--log.level=INFO"
        ports:
            - 80:80
            - 8080:8080
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
    postgre_cookery_2_data:
    pgadmin_cookery_2_data:
