# OpenAPI Generator Plus generator configuration
#
# The path (relative to this configuration file) or a URL for your API specification
inputPath: src/openapi-internal.json

# The path (relative to this configuration file) where the generated API should be output
outputPath: src/tests/openapi-internal

# The name of the generator template used
generator: "@openapi-generator-plus/typescript-fetch-node-client-generator"
# See https://github.com/karlvr/openapi-generator-plus-generators/tree/master/packages/typescript-fetch-node-client#readme for more configuration options
