export enum CUSTOM_ERROR_CODES {
    GENERAL_ERROR = 'GENERAL_ERROR',
    DATABASE_ERROR = 'DATABASE_ERROR',
    NOT_FOUND = 'NOT_FOUND',
    VALIDATION_FAILED = 'VALIDATION_FAILED',
    INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
    FORBIDEN = 'FORBIDEN',
    EXPIRED_TOKEN = 'EXPIRED_TOKEN',
    INVALID_TOKEN = 'INVALID_TOKEN',
    UNIQUE_CONSTRAINT_ERROR = 'UNIQUE_CONSTRAINT_ERROR',
    CONSTRAINT_FAILED = 'CONSTRAINT_FAILED',
    UNABLE_TO_SENT_EMAIL = 'UNABLE_TO_SENT_EMAIL',
    ACCOUNT_DOESNT_EXIST = 'ACCOUNT_DOESNT_EXIST',
}
