name: Docker Image CI

on:
  push:
    tags: [ "*" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag tfilo/my-cookery-book-2-backend:${{steps.vars.outputs.tag}}
      
    - name: Docker push
      run: docker push ${{secrets.DOCKER_USER}}/my-cookery-book-2-backend:${{steps.vars.outputs.tag}}
